version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/ci-cd-test-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - deploy.sh
    - helthCheck.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'